#!/bin/bash
#PBS -l select=1:ncpus=1:mem=8gb
#PBS -l walltime=1:00:00
source ~/anaconda3/etc/profile.d/conda.sh
module load anaconda3/personal intel-suite/2017
conda activate pmp
cp $PBS_O_WORKDIR/fitter.py .
cp $PBS_O_WORKDIR/population.txt .
cp $PBS_O_WORKDIR/Evolution.csv .
cp $PBS_O_WORKDIR/Progress.csv .
cp $PBS_O_WORKDIR/func.py .
cp $PBS_O_WORKDIR/*.txt .
python fitter.py
cp * $PBS_O_WORKDIR